version: 1

disable_existing_loggers: False

handlers:
  rich:
    class: rich.logging.RichHandler
    rich_tracebacks: True

loggers:
  app:
    level: INFO
    handlers: [rich]
    
  library:
    level: INFO
    handlers: [rich]
